---
name: gleam
description: A friendly language for building type-safe, scalable systems!
homepage: https://gleam.run/
licenses:
  - Apache-2.0
languages:
  - Gleam
categories:
  - Compiler
  - Formatter
  - LSP

deprecation:
  message: Gleam's LSP is included in its toolchain, so avoid installing it through Mason to prevent version mismatches. For more details, visit https://gleam.run/language-server/#neovim
  since: v1.0.0

source:
  id: pkg:github/gleam-lang/gleam@v1.2.0
  asset:
    - target: linux_x64
      file: gleam-{{version}}-x86_64-unknown-linux-musl.tar.gz
    - target: linux_arm64
      file: gleam-{{version}}-aarch64-unknown-linux-musl.tar.gz
    - target: darwin_x64
      file: gleam-{{version}}-x86_64-apple-darwin.tar.gz
    - target: darwin_arm64
      file: gleam-{{version}}-aarch64-apple-darwin.tar.gz
    - target: win_x64
      file: gleam-{{version}}-x86_64-pc-windows-msvc.zip

